/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyek;

import java.util.Random;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.text.html.parser.DTDConstants;



/**
 *
 * @author ADMIN
 */
public class NewJFrame_master extends javax.swing.JFrame {

    
    
    
    /**
     * Creates new form NewJFrame_master
     */
    DefaultTableModel model;
    JTable table;
    Object []columnName;
    Object[][] data;
    Random rand;
    String temp="";
    public NewJFrame_master() {
        initComponents();
        rand = new Random();
        
    }
    
    public void tableSetting(int col, int row){
        
        
        
        data = new Object[row][col+1];
        columnName = new Object[col+1];
        
        for (int i = 0; i <= col; i++) {
            if(i==0){
                columnName[0] = "";
            }
            else{
                columnName[i]= i+"";
            }
        }
        
        for (int i = 0; i <row; i++) {
            for (int j = 0; j <=col; j++) {
                if(j==0&&i==row-1){
                    data[i][j]="Hasil : ";
                }
                else if(j==0){
                    data[i][j]=i+1;
                }
            }
        }
        
       
    }
    
    public void loadTable(){
        model = new DefaultTableModel(data, columnName);
        table = new JTable(model);
//       table.setVisible(true);
//        for (Note note : notes) {
//            Object[] obj = {
//                note.getTitle(),
//                note.getContent()
//            };
//            model.addRow(obj);
//        }
        jTable_bilangan.setModel(model);
    }
    
    
    public void randomize(int col, int row){
        
        
        for (int i = 0; i <row; i++) {
            
            for (int j = 0; j <col; j++) {
                int rand_int = 1+ rand.nextInt(10);
                if(j!=0&&i!=row-1){
                    data[i][j]= rand_int;
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_bilangan = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jSpinner_col = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jSpinner_row = new javax.swing.JSpinner();
        jButton_apply = new javax.swing.JButton();
        jButton_randomize = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton_kurang = new javax.swing.JButton();
        jButton_tambah = new javax.swing.JButton();
        jButton_kali = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable_bilangan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable_bilangan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_bilanganMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_bilangan);

        jLabel1.setText("Ukuran");

        jLabel2.setText("x");

        jButton_apply.setText("Apply");
        jButton_apply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_applyActionPerformed(evt);
            }
        });

        jButton_randomize.setText("Randomize");
        jButton_randomize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_randomizeActionPerformed(evt);
            }
        });

        jLabel3.setText("Operasi : ");

        jButton_kurang.setText("-");

        jButton_tambah.setText("+");
        jButton_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_tambahActionPerformed(evt);
            }
        });

        jButton_kali.setText("x");

        jLabel4.setText("Bilangan : ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton_apply)
                                .addGap(18, 18, 18)
                                .addComponent(jButton_randomize))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(60, 60, 60)
                                .addComponent(jSpinner_col, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(jLabel2)
                                .addGap(65, 65, 65)
                                .addComponent(jSpinner_row, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 706, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton_tambah)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton_kurang)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton_kali))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jLabel4)))
                .addContainerGap(353, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jSpinner_col, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jSpinner_row, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_apply)
                    .addComponent(jButton_randomize))
                .addGap(38, 38, 38)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_kurang)
                    .addComponent(jButton_kali)
                    .addComponent(jButton_tambah))
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_applyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_applyActionPerformed
        // TODO add your handling code here:
        int row = Integer.parseInt(jSpinner_col.getValue().toString());
        int col = Integer.parseInt(jSpinner_row.getValue().toString());
        tableSetting(col, row);
        loadTable();
    }//GEN-LAST:event_jButton_applyActionPerformed

    private void jTable_bilanganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_bilanganMouseClicked
        // TODO add your handling code here:
        int row = jTable_bilangan.getSelectedRow();
        int column = jTable_bilangan.getSelectedColumn();
        temp+=table.getValueAt(row, column).toString();
        System.out.println(table.getValueAt(row, column));
        System.out.println(temp);
        if (row==jTable_bilangan.getRowCount()-2){
            for (int i = 0; i <jTable_bilangan.getRowCount(); i++) {
            
                for (int j = 0; j <jTable_bilangan.getColumnCount(); j++) {
                
                    if(j==column&&i==jTable_bilangan.getRowCount()-1){
                        data[i][j]= temp;
                    }
                }
            }
        }
        loadTable();
    }//GEN-LAST:event_jTable_bilanganMouseClicked

    private void jButton_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_tambahActionPerformed
        // TODO add your handling code here:
        int row = jTable_bilangan.getSelectedRow();
        int col = jTable_bilangan.getSelectedColumn();
        if(temp.length()>0){
            char tempChar = temp.charAt(temp.length()-1);
            if(tempChar=='+'||tempChar=='-'||tempChar=='*'){
                temp+="";
            }
            else{
                temp+="+";
            }
        }
        System.out.println(row);
        System.out.println(jTable_bilangan.getRowCount());
        
        
        
    }//GEN-LAST:event_jButton_tambahActionPerformed

    private void jButton_randomizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_randomizeActionPerformed
        // TODO add your handling code here:
        int row = jTable_bilangan.getRowCount();
        int col = jTable_bilangan.getColumnCount();
        randomize(col, row);
        loadTable();
    }//GEN-LAST:event_jButton_randomizeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame_master.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame_master.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame_master.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame_master.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame_master().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_apply;
    private javax.swing.JButton jButton_kali;
    private javax.swing.JButton jButton_kurang;
    private javax.swing.JButton jButton_randomize;
    private javax.swing.JButton jButton_tambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner_col;
    private javax.swing.JSpinner jSpinner_row;
    private javax.swing.JTable jTable_bilangan;
    // End of variables declaration//GEN-END:variables
}
